title:            Michael Timbrook
tagline:          Native and webapp don't go in the same sentance
description:      Software Engineering major at Rochester Institute of Technology
# Your site's domain goes here. Leave localhost server or blank when working locally.
# url:              https://timbrook.im

# Owner/author information
owner:
  name:           Michael Timbrook
  avatar:         http://s.gravatar.com/avatar/86fd22cac0b6714252b9246cd5e03e0a?s=400
  bio:            ""
  email:          timbrook480@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:        7imbrook
  github:         7imbrook
  linkedin:       michaeltimbrook

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-37560133-1
google_verify:            

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Articles
    url: /articles/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    redcarpet

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]